### ISSUE TITLE
[Feature Request] - parser fails when it sees ForwardX11Trusted

### ISSUE THREAD

**Issue by vmiheer** [veeso/ssh2-config#1]
## Description

The parser fails when it sees ForwardX11Trusted option in the config file.

### Changes
1. I think the library can accept this option
or 
2. in the worst case expose a `try_parse` method which can ignore unhandled options

**Comment by veeso** [comment]
Hi, thanks for reporting the issue.

I've fixed this in 0.1.3

**Comment by vmiheer** [comment]
Thank you!
