### ISSUE TITLE
[Feature Request] Expose ignored fields

### ISSUE THREAD

**Issue by dev-ardi** [veeso/ssh2-config#8]
## Description

It would be nice to have them done, but until that's done I think it's better to have a HashMap of Key, Arguments instead of just ignoring them.

## Implementation

Modify the struct so that it holds the hashmap and go through all of the Field variants. This is not too hard to do with a vim macro.

**Comment by dev-ardi** [comment]
Note that I don't need this feature, I just think It'd be positive for the API

**Comment by veeso** [comment]
Thanks for your suggestion. I've implemented it in 0.2.2
